### ISSUE TITLE
Target temperature isn't updated anymore when target_temp_sensor changes

### ISSUE THREAD

**Issue by tubededentifrice** [custom-components/climate.programmable_thermostat#15]
I haven't yet investigated the issue, but it looks like in the latest 5.1 the target temperature doesn't change anymore when the value of target_temp_sensor changes (ie for example it stays at 20 whereas target_temp_sensor value is now 21). I've downgraded to 4.3 and it works fine there.

**Comment by MapoDan** [comment]
Ciao,
I suppose that you are using the hot mode as automatic, right?
If yes, as per [breaking change list](https://github.com/custom-components/climate.programmable_thermostat/releases/tag/5.0) of version 5.0 I have swap manual and automatic mode to make more well integrated with Alexa and so on.
Now manual are mode `heat` and `cold`, while the automatic is `heat_cool`.

Let me know if it is like that so I close the issue.

**Comment by tubededentifrice** [comment]
I'm using the defaults, so I though those breaking changes didn't apply. I'm only using heaters, so I assumed it should do it's basic job "out of the box", quite confusing.

I'm still not sure I understand nor the purpose of this change nor what needs to be changed exactly, but I'll try things in a minute and report back.

**Comment by tubededentifrice** [comment]
I think the real issue was that I was using the wrong modes as you said, due to not using the thermostat cards I didn't notice it, much clearer now. I've still a few things to try before closing this issue. Thanks for your help.

**Comment by gdistasi** [comment]
Hi, I have a note regarding the manual mode. If you are in heat mode and you restart HA, it gets the target temperature from the target sensor instead of restoring the temperature before the HA restarting.
