### ISSUE TITLE
Component shows heating when it is off and has to be off

### ISSUE THREAD

**Issue by klejejs** [custom-components/climate.programmable_thermostat#17]
Target temperature is set to 20, current temperature is 22, thermostat is not heating, however, it's status is showing as heating.

Home Assistant version: 0.110
Component version: 6.1

**Comment by MapoDan** [comment]
You are right, I just noticed it, I will have a look and update you here once fixed.

**Comment by klejejs** [comment]
Thank you!

**Comment by MapoDan** [comment]
Ciao,
I should have solved the issue with version 6.3 just released.
Let me know if it fix your issue.

Be aware the that the action showed can still say heating (I still have to fix that), but the switch is turned off.

**Comment by klejejs** [comment]
Thank you very much! Can you please post here, when you fix the action showed?

**Comment by MapoDan** [comment]
Ciao!
Version 7.0 now is correctly showing the action!
I'm closing the issue. If you notice something, let me know.
