### ISSUE TITLE
Feature Request - Add min_cycle_duration

### ISSUE THREAD

**Issue by mikesmitty** [custom-components/climate.programmable_thermostat#19]
Would it be possible to add a `min_cycle_duration` option like on the Home Assistant `generic_thermostat`? https://www.home-assistant.io/integrations/generic_thermostat/#min_cycle_duration
I have an A/C unit on a smart plug that I'd like to make sure doesn't cycle on/off too quickly to avoid burning it out.

**Comment by MapoDan** [comment]
Ciao,

From version 7.0 this will be included.
I'm testing it and finalizing the config_flow but it seems working.
I'll post here once released.

**Comment by MapoDan** [comment]
Ciao!
Released! Version 7.0 now has min_cycle_duration option!
