### ISSUE TITLE
Cannot set Dry Mode

### ISSUE THREAD

**Issue by fudu** [custom-components/climate.programmable_thermostat#28]
As in subject, I don't understand if it's possibile to have "Dry" in Hvac_Modes

Thanks

**Comment by MapoDan** [comment]
No, there is no dry mode at the moment. you have only heat, cool, auto (heat_cool) and off.
This integration is not planned to activate speific mode of devices, but just to open/close, activate/deactivate devices.

**Comment by fudu** [comment]
> This integration is not planned to activate speific mode of devices, but just to open/close, activate/deactivate devices.

Ok.
I'm not interested in activate switch (as heater or cooler has to be defined, I'm using virtual switches), but I'm using it and its states to manage other devices (TRV, heater_pump, air conditioner...) with a thermostat interface.
So it would be useful to have Dry mode available.
Thanks

**Comment by hugalafutro** [comment]
I'm in complete opposite camp as I only turn on/off 1 heater according to reading from 1 thermometer so this is exactly and only thing I need, but maybe https://github.com/ciotlosm/lovelace-thermostat-dark-card is something you could use?

"hvac | object | optional | Allows mapping of custom states or using a custom sensor/attribute for state"

**Comment by MapoDan** [comment]
Ciao, the link you posted is related to a Lovelace card that display only integration.
Let me close this thread..
