### ISSUE TITLE
(enhancement) Allow setting of step size when manually adjusting temp

### ISSUE THREAD

**Issue by hugalafutro** [custom-components/climate.programmable_thermostat#29]
Hi,
as the title says, I would find it useful if the step would be configurable as I'd like it at 0.1 currently it jumps by 0.5. I use your thermostat to turn on/off 1 heater in 1 small room and sometimes 21 is too cold and 21.5 is too hot :D 

The only way I found is to tell Alexa to set the thermostat to certain value.

**Comment by MapoDan** [comment]
Ok, I'll take care of it.
I'll warn you here when it will be delivered.

**Comment by MapoDan** [comment]
Ciao,

I had a look.
What you are requesting is not related to integration but to card.
Itegration is going to accept any value of temp, no particular requirements for number precision. Indeed, if you set manually a value between 21 and 21.5 it will be accepted.
If you want to achieve that you have to use a card that allows you to define minimum step. Default card is no allowing that.

So I'm closing the issue.

Ciao
Daniele
