### ISSUE TITLE
Error Unable to find services.yaml for the programmable_thermostat integration

### ISSUE THREAD

**Issue by zuscu** [custom-components/climate.programmable_thermostat#30]
Hola.
Es la segunda vez que lo intento con este componente. La primera vez tuve problemas porque tenía un script que arrancaba el switch y el componente paraba el switch incluso aunque tuviese en apagado el compontente.
He querido darle otra oportunidad pero ahora no me arranca el switch y me da el siguiente error:

Unable to find services.yaml for the programmable_thermostat integration

¿Cuál puede ser el problema?

Hi.
This is the second time I have tried this component. The first time I had problems because I had a script that started the switch and the component stopped the switch even if I had the component turned off.
I wanted to give it another try but now the switch does not start and gives me the following error:

Unable to find services.yaml for the programmable_thermostat integration

What could be the problem?

**Comment by zuscu** [comment]
Buenos días.
Ayer, después de 3 intentos conseguí que al menos funcionara de forma manual, estableciendo el valor en el componente arrancaba la caldera de gas y paraba al llegar a la temperatura establecida manualmente.
No consigo que funcione de forma automática, tengo los valores establecidos en un componente file_restore. Arranco la integración con el modo apagado, por si algún día se me va la luz no arranque directamente la caldera de forma innecesaria. Al poner el modo heat-cool el sistema no marca la temperatura objetivo, simplemente se queda en el valor mínimo del rango que he establecido en el componente.
Pongo a continuación los valores que tengo establecidos en la integración.

Muchas gracias.

Un saludo.

Good Morning.
Yesterday, after 3 attempts I got it to work at least manually, setting the value in the component started the gas boiler and stopped when it reached the manually set temperature.
I can't get it to work automatically, I have the values set in a file_restore component. I start the integration with the off mode, in case some day the power goes out, do not start the boiler directly unnecessarily. When putting the heat-cool mode the system does not mark the target temperature, it simply stays at the minimum value of the range that I have established in the component.
I put below the values that I have established in the integration.

Thank you.

Best regards

{
                "entry_id": "1626f4616b0f30de22defb98b951cd4d",
                "version": 3,
                "domain": "programmable_thermostat",
                "title": "Termostato",
                "data": {
                    "unique_id": "5bd8d0d5-281a-4875-abee-a9fe8db53c8b",
                    "name": "Termostato",
                    "heater": [
                        "switch.shelly1_caldera"
                    ],
                    "actual_temp_sensor": "sensor.temperature_158d000418e3ce",
                    "target_temp_sensor": " sensor.temperaturas",
                    "max_temp": 25,
                    "min_temp": 15,
                    "tolerance": 0.5,
                    "hvac_options": 7,
                    "auto_mode": "all",
                    "initial_hvac_mode": "off",
                    "min_cycle_duration": {
                        "hours": null,
                        "minutes": "30",
                        "seconds": "00"
                    }
                },
                "options": {},
                "system_options": {
                    "disable_new_entities": false
                },
                "source": "user",
                "connection_class": "local_poll",
                "unique_id": null
            }

![image](https://user-images.githubusercontent.com/73275754/101730523-779c6b80-3aba-11eb-89ba-dc0dc85796dd.png)

![image](https://user-images.githubusercontent.com/73275754/101730566-8c78ff00-3aba-11eb-8021-2aef07fa808f.png)

**Comment by MapoDan** [comment]
Ciao zuscu,

About your first message:
The component is managing the heater and cooler system, so when it is off  it will turn all switches off.
About the 'services.yaml' issue, to be honest I've no clue. You are the first one getting this error and the services used and available for this integration are supplied by climate platform.
Can you give more info about that?

About the second topic.. That's strange.
What is more strange is that in the card you should see the actual temperature (the big number you have) and set temperature smaller (that you miss), so the issue baybe lay on setup of file restore component..

Let me know if it help and provide me that set up too, thanks.
Daniele

**Comment by zuscu** [comment]
Hola de nuevo y perdón por haber tardado en responder.

A la cuarta vez que hice los mismos pasos el sistema se ha montado correctamente y ahora funciona todo correctamente, pero me costó bastante conseguirlo.

El mensaje cambio de Error a Warning y aún lo sigue mostrando pero parece no afectarle, supongo que espera un comportamiento y al no hacerlo muestra el aviso.

Te agradezco todo el trabajo realizado y la paciencia de soportar a usuarios como yo.

Me gustaría de paso poder hacerte una petición, si es posible, ¿habría forma de que cuando se establezca la temperatura en formato manual el sistema te pregunte cuantas horas ha de estar a esa temperatura antes de volver a la temperatura marcada como objetivo en el momento que acabe?

Siempre que he tenido programadores me ha gustado esa forma de trabajar, establezco de forma manual 20 grados y le digo que lo mantenga durante 2 horas, de esa manera una vez que acaba el tiempo fijado el sistema vuelve sólo a la temperatura objetivo y de esa forma no te olvidas la calefacción encendida sin querer.

Otra cosa son las temperaturas fijadas para la noche o para que arranque justo antes de llegar a casa, etc.

Sé que con el móvil ahora lo puedo hacer, pero si es programable que funcione como tal, ¿no?.

Un saludo y muchas gracias.

Hello again and sorry for being slow to respond.

The fourth time I did the same steps the system has been mounted correctly and now everything works correctly, but it took me a lot to get it.

The message changed from Error to Warning and it still shows it but it doesn't seem to affect it, I guess it expects a behavior and by not doing it it shows the warning.

I appreciate all the work done and the patience to support users like me.

I would like to be able to make a request to you, if possible, would there be a way that when the temperature is set in manual format the system will ask you how many hours it has to be at that temperature before returning to the target temperature at the moment what ends?

Whenever I have had programmers I have liked that way of working, I manually set 20 degrees and tell them to keep it for 2 hours, that way once the set time is over the system returns only to the target temperature and from that way you don't forget the heating turned on accidentally.

Another thing is the temperatures set for the night or to start just before arriving home, etc.

I know that now I can do it with the mobile, but if it is programmable that it works as such, right?

Regards, and thank you very much.

![image](https://user-images.githubusercontent.com/73275754/102194033-1828cc00-3ebd-11eb-8ae6-3eba0ebdf11d.png)

**Comment by MapoDan** [comment]
Ciao,

services.yaml added in version 7.4 that has been just released.

About the second topic.
What you want to obtain is not in the scope of thermostat. you have to achive it with external automations or achive it through the file restore.
