### ISSUE TITLE
Version key in manifest file

### ISSUE THREAD

**Issue by LEJOUI** [custom-components/climate.programmable_thermostat#35]
Updating to the latest beta of HA gives the following warning

`No 'version' key in the manifest file for custom integration 'programmable_thermostat'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'programmable_thermostat`

More information can be found here
https://www.home-assistant.io/blog/2021/03/03/release-20213/#breaking-changes

edit: changed link

**Comment by MapoDan** [comment]
Solved in version 8.1
