### ISSUE TITLE
would it be possible?

### ISSUE THREAD

**Issue by JoseCarlos-Balan** [custom-components/climate.programmable_thermostat#36]
Hello, first to congratulate you on the work, secondly it would be able that the thermostat also sends options to change temperature (SERVICE CLIMATE.SET_TEMPERATURE), maybe put that when it is in cool it sends option of -2 degrees to the ac or when it is in heat it sends option of +2.
Another thing that I thought is that instead of working as a swift it is possible that it works with the parameters of climate.turn_on and climate.turn_off

**Comment by vinnyfuria** [comment]
I'm a project user, not a contributor; all these service calls are currently supported (assuming the HVAC options are configured to allow them) and I can confirm that they (`climate.set_temperature`, `climate.turn_on`, and `climate.turn_off`) all work as expected.

**Comment by MapoDan** [comment]
As Vinnyfuria said everything is supported ;)
