### ISSUE TITLE
Cannot add any sensor

### ISSUE THREAD

**Issue by RoSulek1** [custom-components/climate.programmable_thermostat#38]
Plannned temperature sensor is not existing into Home Assistant.

**Comment by MapoDan** [comment]
Ciao,
You have to create it.
One option is my other component https://github.com/custom-components/sensor.file_restore
With this you can create a file in the HA folder with the list of values and get the right value.
Please read documentation, it should explain everything.

My setup is: programmable_thermostat to control temperature; it gets target temperature from file_restore. file_restore sensor is filled via UI using a combination of input_selects, input_numbers, scripts, notify components

Ciao
Daniale
