### ISSUE TITLE
Switching on heater when above set point

### ISSUE THREAD

**Issue by mikesumbler** [custom-components/climate.programmable_thermostat#46]
Hi

Thermostat appears to be coming on at night when it is quite far above the target setpoint:

I have an auotmation in place to drop the set point at night (a zwave thermostat - HR4ZW). This is picked up on the control in HA but looking this morning (and other days) appears to still be triggering heating around 19.5degrees against set point of 18. There is no heating mode shown as well at these times

History from prog_thermostat:

![image](https://user-images.githubusercontent.com/6397889/143029385-21a79677-6bfe-41b4-9329-ab2e864f768b.png)

History on switch to boiler (comes on at night so is being triggered):

![image](https://user-images.githubusercontent.com/6397889/143029944-cdb90bd3-af13-4467-ba59-d0a64adc98f9.png)

Any suggestions?

Mike

**Comment by mikesumbler** [comment]
Ok found my own issue (again) - I added the thermostat as an integration and used the helper to populate the parameters then also created another programmable_thermostat in the yaml. 

General question - can I delete the thermostat from the integrations page and still have the thermostat in the yaml be functional and read into the config.

**Comment by MapoDan** [comment]
Ciao,

yes, of course, the YAML and Integration are independent, so you can remove from one of them and the other will keep working.
