### ISSUE TITLE
I've installed this but no integration appears..?

### ISSUE THREAD

**Issue by UnbridledGames** [custom-components/climate.programmable_thermostat#47]
I installed this through HACS, and restarted (twice). But no integration appears. Do I need to configure this completely manually? The readme says "just configure all the entities you want through the user interface" and that leads me to believe I can use the web UI to configure this.

But after install, nothing shows up under integrations. When I search to add, nothing new appears when I search for 'programmable' or 'thermostat'.

Am I missing something?

**Comment by mdeweerd** [comment]
In my case, "Add integration" is available, but currently configuring using the UI is not the best option.  When you want to change part of the configuration, you can't beause of a bug.

**Comment by MapoDan** [comment]
Ciao

@UnbridledGames to be honest I don't know. I had the same issue when I started dev this. I restarted few times and the whole OS and after some time it appeared.
Have you solved it?

Sorry for not being helpful, but I'm not at all an expert :)

**Comment by MapoDan** [comment]
Closed for inactivity
