### ISSUE TITLE
Heater doesn't turn off

### ISSUE THREAD

**Issue by flixerator** [custom-components/climate.programmable_thermostat#53]
Hello, thank you for great product, but t doesn't work for me properly(it doesn't turn off the valve, it can only turn it on)here is my config and logs
climate:
  - platform: programmable_thermostat
    name: room225
    heater: 
      - climate.0xcc86ecfffec39aa0
    actual_temp_sensor: sensor.0x00158d0006a070ba_temperature
    min_temp: 10
    max_temp: 30
    target_temp_sensor: sensor.target_bedroom
    tolerance: 0.5
    auto_mode: heating
    hvac_options: 3
    min_cycle_duration:
      seconds: 50

Logger: homeassistant.helpers.template
Source: helpers/template.py:1779
First occurred: 01:32:20 (4 occurrences)
Last logged: 01:32:32

Template variable warning: dict object has no element Undefined when rendering '{% set values = {'idle':'off','heat':'heating','cool':'cooling','fan only':'fan'} %}{{ values[value_json.running_state] }}'
Logger: homeassistant.components.mqtt.climate
Source: components/mqtt/climate.py:413
Integration: MQTT (documentation, issues)
First occurred: 01:32:20 (4 occurrences)
Last logged: 01:32:32

Invalid ['off', 'heating', 'cooling', 'drying', 'idle', 'fan'] action:

tell me if you need anything else, i am a bit newbie in HA but I'll try to find any other logs or info
Hope you can help me

**Comment by jsiemek** [comment]
Great work with programmable_thermostat!

I can confirm. I use programmable_thermostat to control geckos temperature. 
At the evening day thermostat goes off, but hater lamp remain on.

**Comment by MapoDan** [comment]
Ciao,

your heater/cooler has the service turn_off available?

**Comment by MapoDan** [comment]
It may be also the min_cycle_duration as per issue #52

**Comment by jump396** [comment]
I have the same problem, It doesnt turn off.
Could i verify something?
I invoke the service climate.turn_off but It doesnt turn off sometime.

**Comment by MapoDan** [comment]
Probably you have set min_duration_cycle. check it.
Check also #52
