### ISSUE TITLE
Set target temperature via entities

### ISSUE THREAD

**Issue by Gontash** [custom-components/climate.programmable_thermostat#54]
Is it possible to set/change the target temperature via entities? I try to change value in `target_temp_sensor: sensor.program_temperature` but nothing has changed.

**Comment by MapoDan** [comment]
Ciao, 
The scope of this integration is exactly that.
You have to set target_temp_sensor parameter with an entity that has a value in the state.
This is working since I have it in my configuration. So there is something badly set somewhere else.

**Comment by MapoDan** [comment]
Closed. Evreything is described in specifications.
