### ISSUE TITLE
Heating and cooling control with a single switch.

### ISSUE THREAD

**Issue by Anzic23** [custom-components/climate.programmable_thermostat#56]
I'm trying to set up fan coil control with your component. The task is as follows:
The fan coil operates in two modes, heating only and cooling only (summer/winter mode). In summer mode, the thermostat turns on the relay until the current temperature drops to the set temperature. Then it turns off until the current temperature exceeds the desired one.
In winter mode, the thermostat turns on if the current temperature is LOWER than the set one, and heats up until the current temperature INCREASES to the set one, then turns off.
The question is, is it possible to somehow bind the logic of the summer / winter modes to your component? Ideally, removing the "automatic" mode.

**Comment by MapoDan** [comment]
Ciao,
Yes, the integration should allow to set heaters and coolers to the same value since version 7.6

**Comment by Anzic23** [comment]
You are right, you can specify one device for heating and cooling. I created 2 virtual switches and 4 automations. It is a pity that I did not check this possibility right away. Thanks for the tip!
