### ISSUE TITLE
Is this integration still being maintained?

### ISSUE THREAD

**Issue by ovizii** [custom-components/climate.programmable_thermostat#58]
I can see plenty of open issues dated mostly about 12 months back, so I am hesitant about using it.

**Comment by MapoDan** [comment]
Ciao, I'm the owner of this. 
I was off this topic for a long time, I'll try to come on the topic in the next months.
In any case there are some things that I don't know how to fix (I'm not an expert on dev) so this is why they are so old..
By the way, the integration is working in this moment and I'm using it.

**Comment by ovizii** [comment]
Thanks for the update. Have a look at this one, maybe there's some opportunity for collaboration? https://github.com/KartoffelToby/better_thermostat
