### ISSUE TITLE
target_temp_sensor

### ISSUE THREAD

**Issue by rbjoensen** [custom-components/climate.programmable_thermostat#61]
Hello and thanks for the integration. 
I have challenges with target_temp_sensor. 
How is it supposed to be used? My wish is to raise the temperature  by 0.5 degrees under specific circumstances. 
Greetings RBJ

**Comment by MapoDan** [comment]
Ciao,
it is a generic sensor that has as state a number and the thermostat will activate cool or heat trying to reach that target temp.

To achive your scope:
if you want to rise the temp of the room of 0.5 degree you can try using a template sensor
