### ISSUE TITLE
'custom_components.programmable_thermostat.climate.ProgrammableThermostat' is using self.async_update_ha_state()

### ISSUE THREAD

**Issue by litinoveweedle** [custom-components/climate.programmable_thermostat#66]
When used with HA 2023.5.4 it reports warning as bellow:

Entity climate.xxxxx (<class 'custom_components.programmable_thermostat.climate.ProgrammableThermostat'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.

**Comment by MapoDan** [comment]
Solved with latest release 8.3
